# Generated by Django 2.1.5 on 2019-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crunchbaseURI', models.URLField()),
                ('githubContributorsCount', models.IntegerField()),
                ('githubLatestCommitDate', models.TimeField()),
                ('githubStars', models.IntegerField()),
                ('homepage', models.URLField()),
                ('HQ', models.TextField()),
                ('latestTweetDate', models.TimeField()),
                ('logoURI', models.URLField()),
                ('organization', models.TextField()),
                ('SVCUrl', models.URLField()),
                ('twitterURI', models.URLField()),
            ],
        ),
    ]
