# Generated by Django 2.1.5 on 2019-01-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disyo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsapplication',
            name='id',
        ),
        migrations.AddField(
            model_name='dsapplication',
            name='name',
            field=models.CharField(default='aaaa', max_length=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
