# Generated by Django 2.1.5 on 2019-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disyo', '0002_auto_20190122_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsapplication',
            name='githubLatestCommitDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dsapplication',
            name='latestTweetDate',
            field=models.DateTimeField(),
        ),
    ]
